export enum StationState {
	ACTIVE = "ACTIVE",
	INACTIVE = "INACTIVE",
	MAINTENANCE = "MAINTENANCE",
	OUT_OF_SERVICE = "OUT_OF_SERVICE",
	BROKEN = "BROKEN",
	DAMAGED = "DAMAGED",
	DECENT = "DECENT",
	GOOD = "GOOD",
	PRIME = "PRIME",
}