######################################################
### Create PlugType
### Expected : 201 + tâche créée
POST http://localhost:8080/api/plugtypes
Content-Type: application/json

{
    "plugName": "Type S",
}
######################################################

######################################################
### List all PlugTypes
### Expected : 200 + liste JSON
GET http://localhost:8080/api/plugtypes
######################################################

######################################################
### Get a PlugType By ID (exemple avec id=1)
### Expected : 200 ou 404

### Valid Request
GET http://localhost:8080/api/plugtypes/1
### Invalid Request
GET http://localhost:8080/api/plugtypes/1234567890987654
######################################################

######################################################
### Modifier une article (exemple avec id=1)
### Expected : 200 ou 404

### Invalid Request
PUT http://localhost:8080/api/plugtypes/1
Content-Type: application/json

{
    "plugName": "Type M",
}

### Invalid Request
PUT http://localhost:8080/api/plugtypes/1234567890987654
Content-Type: application/json

{
    "plugName": "Type M",
}
######################################################

######################################################
### Supprimer une article (exemple avec id=1)
### Expected : 200 ou 404

### Valid Request
DELETE http://localhost:8080/api/plugtypes/1    
### Invalid Request
DELETE http://localhost:8080/api/plugtypes/1234567890987654
######################################################